version: '3.8'

services:
  backend:
    container_name: twitter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: twitter_activity
    command: npm run start:dev

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_activity
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
